animory/build.gradle
animory/src/main/resources/application.yml

문서 작업입니다.
resolve #9 
resolve #11

기본 properties 설정, build.gradle 가독성 개선

---

.github/workflows/gradle-test.yml

- develop branch로 PR 발생 시 gradle 테스트를 수행하고, 실패 시 PR에 comment를 자동으로 추가해주는 workflow 파일을 추가하였습니다.
Close #16

GitHub Actions Workflows 테스트 자동화 추가

---

README.md

- 프로젝트 생성 이후,
docs 폴더 경로가 바뀌면서
README.md 파일에서 참조하고 있는 로고 파일의 경로가 바뀌었습니다.

Logo 파일 경로 수정

---

.github/workflows/gradle-test.yml

backend-test -> gradle-test
이름이 조금 더 구체적입니다.

GitHub Actions Test workflow job name 수정

---

animory/src/main/java/com/daggle/animory/common/error/GlobalExceptionHandler.java
animory/src/main/java/com/daggle/animory/common/error/GlobalValidationHandler.java
animory/src/main/java/com/daggle/animory/common/error/exception/BadRequest400.java
animory/src/main/java/com/daggle/animory/common/error/exception/Forbidden403.java
animory/src/main/java/com/daggle/animory/common/error/exception/InternalServerError500.java
animory/src/main/java/com/daggle/animory/common/error/exception/NotFound404.java
animory/src/main/java/com/daggle/animory/common/error/exception/UnAuthorized401.java

- 단순한 디렉토리 통합 입니다. 코드의 변경사항은 없습니다.
Close #26

_core 패키지를 commons 패키지로 통합

---

animory/src/main/java/com/daggle/animory/model/Province.java
animory/src/main/java/com/daggle/animory/model/ShelterAddress.java
animory/src/main/java/com/daggle/animory/shortform/ShortFormController.java
animory/src/main/java/com/daggle/animory/shortform/ShortFormService.java
animory/src/main/java/com/daggle/animory/shortform/dto/request/ShortFormSearchCondition.java
animory/src/main/java/com/daggle/animory/shortform/dto/response/CategoryShortFormPage.java
animory/src/main/java/com/daggle/animory/shortform/dto/response/HomeShortFormPage.java
animory/src/main/java/com/daggle/animory/shortform/dto/response/ShortFormDto.java
animory/src/main/java/com/daggle/animory/shortform/dto/response/ShortFormPage.java
animory/src/test/java/com/daggle/animory/shortform/ShortFormControllerTest.java

- **[꼭 확인해주세요] 추가적으로, ShelterAddress 의 province를 enum 타입으로 만들어두었습니다. (Province)**
- ShortForm Controller 생성하였습니다.
- API 명세에 맞게 요청/응답 형식 만들어두었습니다. (수정사항 없음)
- 입력 값이 제대로 들어가는지 정도 테스트 작성해두었습니다.
- 비즈니스 로직이나 DB 참조하는 부분은 PetRepository 쪽이 추가된 이후에 생각해보려고 아직 구현하지 않았습니다.
Close #24 
Close #28

ShortForm API 기초 구현

---

animory/src/main/java/com/daggle/animory/common/error/GlobalExceptionHandler.java
animory/src/main/java/com/daggle/animory/shortform/ShortFormService.java
animory/src/main/resources/application.yml

- Exception.class Internal Server Error를 Handler에 추가하였습니다.
- Runtime Exception이 아닌, Servlet Exception 으로 잡히는 예외들 추가하였습니다.
Close #35

Exception handler class 추가

---

animory/src/main/resources/application.yml

Fix swagger proxy problem. swagger path, server forward headers strategy

---

animory/build.gradle
animory/src/main/java/com/daggle/animory/common/config/SpringDocConfiguration.java
animory/src/main/java/com/daggle/animory/common/config/SpringSecurityConfiguration.java

- SpringDoc 설정 (title, description, test server url 등)
- CORS 설정 (Spring Security 의존성 추가)
- Spring Security 는 CORS, CSRF disable 설정만 해두었습니다.
Close #39

Springdoc, CORS(Spring security) 설정 추가

---

.github/workflows/deploy-trigger.yml

- GitHub Actions workflow를 사용하여, 원격 서버의 배포 스크립트를 작동시키는 API를 호출합니다. key는 GitHub secrets를 사용하였습니다.
- BE 프로젝트의 경우, main, develop branches 에 push가 발생할 때마다 작동.
- FE 프로젝트는 내부 파일을 건드리지 않기 위해, 매 시간 주기적으로 polling 하는 방식으로 설정해두었습니다.
- 참조하는 branch는 둘 다 `develop` 입니다. 매 빌드 시 마다 내용을 모두 삭제하지 않고, develop branch의 변경사항을 pull 받아와서 작업합니다.
Close #25

개발 환경의 배포 자동화 구축

---

.github/workflows/gradle-test.yml
animory/files_upload_location/20230928103040_test1.mp4
animory/files_upload_location/20230928103040_test2.jpeg
animory/files_upload_location/20230930055151_test1.mp4
animory/files_upload_location/20230930055151_test2.jpeg
animory/files_upload_location/20230930071506_test1.mp4
animory/files_upload_location/20230930071506_test2.jpeg
animory/src/main/java/com/daggle/animory/common/error/GlobalValidationHandler.java
animory/src/main/java/com/daggle/animory/common/error/exception/BadRequest400.java
animory/src/main/java/com/daggle/animory/common/error/exception/Forbidden403.java
animory/src/main/java/com/daggle/animory/common/error/exception/InternalServerError500.java
animory/src/main/java/com/daggle/animory/common/error/exception/NotFound404.java
animory/src/main/java/com/daggle/animory/common/error/exception/UnAuthorized401.java
animory/src/main/java/com/daggle/animory/controller/pet/PetController.java
animory/src/main/java/com/daggle/animory/service/pet/PetService.java
animory/src/main/java/com/daggle/animory/service/pet/fileIO/FileStorageService.java
animory/src/main/java/com/daggle/animory/service/pet/fileIO/PetFileStorageService.java
animory/src/main/resources/application.yml
animory/src/test/java/com/daggle/animory/controller/pet/PetControllerTest.java
animory/src/test/java/com/daggle/animory/shortform/ShortFormControllerTest.java

- PetController와 PetService를 만들었습니다. 다만 동영상 및 이미지 업로드 서비스는 추후 처리의 용이함을 위해 PetFileStorageService로 분리하였습니다.
- PetController 부분에 PetRequestDTO를 string으로 받은 건 아직 해당 DTO를 만들지 못해 그런 것이므로 추후 만들어지면 변경하겠습니다.
- 뭔가 오류가 빵빵터지고 그럴 줄 알았는데 아무 오류가 없어서 더 당황스럽네요;;
- 지적은 환영입니다 언제든지 지적해주세요 
- 계속 수정하고 commit 한 결과 새로운 무언가가 생성되어서 터지는 오류는 아닌 것 같습니다. Deprecated Gradle features were used in this build 가 뜨는데 제가 github actions를 써보질 않아서 뭘 손대야 할지 모르겠네요
- mockMVC가 multipart 파일도 mock 객체로 만들어주더라구요... 참 편했습니다. 굳이 실제 파일 업로드 안해도 되고 좋네요
Close #31 
Close #30

Feat/#31 PetController 및  PetService 생성, 파일 업로드 테스트, Fix/#30 alidationHandler 범위 수정

---

README.md

- 요구사항 명세 Wiki 링크 추가
- 피그마 UI 페이지 링크 추가
- 배포된 인스턴스 주소 추가
- 배포된 API 문서 페이지 추가
- ERD 페이지 추가(프로젝트 폴더 내부 캡쳐본)
Close #48

프로젝트 설명 추가 (README.md)

---

animory/src/main/java/com/daggle/animory/common/error/GlobalExceptionHandler.java
animory/src/main/java/com/daggle/animory/domain/pet/PetController.java

- MultiPartFile Upload 시, 설정된 Size를 초과하는 파일 업로드 또는 전체 Request 의 Size가 설정된 값을 초과할 때 발생하는 오류 처리입니다.
- 이 보다 앞에서 처리하는 tomcat 의 max-swallow-size 설정의 기본값이 2MB라는 것을 확인했는데, 따로 관리하지 않아도 되는지 테스트해보지를 않았습니다.
- 추가로 Max Upload Size 값을 이야기해볼필요가 있을 것 같습니다.
Close #49

MaxUploadSizeExceededExcetion Handler 추가

---

animory/src/main/java/com/daggle/animory/domain/account/AccountController.java
animory/src/main/java/com/daggle/animory/domain/account/AccountService.java
animory/src/main/java/com/daggle/animory/domain/account/dto/request/AccountLoginDto.java
animory/src/main/java/com/daggle/animory/domain/account/dto/request/EmailValidateDto.java
animory/src/main/java/com/daggle/animory/domain/account/dto/request/ShelterAddressSignUpDto.java
animory/src/main/java/com/daggle/animory/domain/account/dto/request/ShelterSignUpDto.java
animory/src/main/java/com/daggle/animory/domain/account/dto/response/AccountLoginSuccessDto.java

- 계정 컨트롤러단 구현
- 로그인 API 기초 생성
- 회원가입 API 기초 생성
- 이메일 중복 검사 API 기초 생성
- 각 요청 및 응답에 맞는 DTO 구현
Close #65

계정 컨트롤러단 기초 구현

---

animory/build.gradle
animory/src/main/java/com/daggle/animory/AnimoryApplication.java
animory/src/main/java/com/daggle/animory/domain/pet/PetController.java
animory/src/main/java/com/daggle/animory/domain/pet/service/PetService.java
animory/src/main/java/com/daggle/animory/domain/pet/service/fileIO/FileStorageService.java
animory/src/main/java/com/daggle/animory/domain/pet/service/fileIO/PetFileStorageService.java
animory/src/main/java/com/daggle/animory/domain/pet/util/PetAgeToBirthDateConverter.java
animory/src/test/java/com/daggle/animory/domain/pet/service/PetAgeToBirthDateConverterTest.java

- Pet Age <-> BirthDate 변환 구현체 추가 (0년0개월 <-> 2023-10-02)
- AutoParams 라이브러리 추가 (테스트 코드 부분을 보시면 사용법을 파악하기 좋습니다)
- SpringBoot TimeZone 설정 추가
Close #55 ,
Close #58 ,
Close #64

Pet Age와 BirthDate 간 변환을 위한 유틸리티 클래스 추가

---

animory/src/main/java/com/daggle/animory/common/security/TokenProvider.java
animory/src/main/java/com/daggle/animory/common/security/UserDetailsImpl.java
animory/src/main/java/com/daggle/animory/common/security/UserDetailsServiceImpl.java
animory/src/main/java/com/daggle/animory/domain/account/AccountController.java
animory/src/main/java/com/daggle/animory/domain/account/dto/request/EmailValidateDto.java
animory/src/main/java/com/daggle/animory/domain/account/dto/request/ShelterAddressSignUpDto.java
animory/src/main/java/com/daggle/animory/domain/account/dto/request/ShelterSignUpDto.java
animory/src/main/java/com/daggle/animory/domain/shelter/ShelterRepository.java
animory/src/main/resources/application.yml
animory/src/test/java/com/daggle/animory/domain/shortform/ShortFormControllerTest.java

- 회원가입 request Dto에 우편번호 추가
- UserDetailsServiceImpl 수정
- UserDetailImpl getAuthorities() 메서드 수정
- 토큰 유효 시간 수정
- dto 유효성 검증 부분 수정
- 비밀번호 정규식 수정
- 피어리뷰 피드백 반영
Close #70

시큐리티 설정 수정 및 피드백 반영

---

animory/src/main/resources/application-production.yml

- 운영 환경에서 사용할 profile 설정파일 application-production.yml 추가하고, 배포서버에서 생성되는 Dockerfile 에 환경변수 설정 추가하였습니다.
Close #76

운영환경 프로필설정 jwt secret, file-server-domain

---

animory/.gitignore
animory/src/main/java/com/daggle/animory/domain/fileserver/FileController.java
animory/src/main/java/com/daggle/animory/domain/fileserver/FileRepository.java
animory/src/main/java/com/daggle/animory/domain/fileserver/LocalFileRepository.java
animory/src/main/resources/application-production.yml
animory/src/main/resources/application.yml
animory/src/test/java/com/daggle/animory/domain/fileserver/FileControllerTest.java
animory/src/test/java/com/daggle/animory/domain/fileserver/LocalFileRepositoryTest.java

- FileRepository 를 JPA Repository와 같은 수준으로 추상화 하였습니다.(method 이름을 save, findByName 으로 바꿨습니다)
- 저장 완료 이후, 반환 값에 클라이언트 입장에서 필요한 full request url (domain 을 포함한) 을 제공하도록 변경했습니다.
- 코드 가독성을 약간 개선하였습니다.
Close #85

로컬 파일서버와 테스트

---

animory/.gitignore
animory/src/main/java/com/daggle/animory/common/config/WebConfiguration.java
animory/src/main/java/com/daggle/animory/common/error/GlobalExceptionHandler.java
animory/src/main/java/com/daggle/animory/common/logger/MethodExecutionTimeLogger.java
animory/src/main/java/com/daggle/animory/common/logger/RequestLogger.java
animory/src/main/resources/logback-spring.xml
animory/src/main/resources/logger/console/console-appender.xml
animory/src/main/resources/logger/console/parameter-appender.xml
animory/src/main/resources/logger/file/error-appender.xml
animory/src/main/resources/logger/file/info-appender.xml
animory/src/main/resources/logger/file/warn-appender.xml
animory/src/main/resources/logger/property.xml

- logback 설정파일(logback-spring.xml, logger, pattern layout 등..) 추가
- method 실행시간 측정 aspect 등록 + log 추가
- request log interceptor 추가
- ModelAttribute type으로 parameter를 받고있는 `/short-forms` endpoint 에서 Exception 처리가 잘 안되는 것 같습니다. parameter를 넣지 않고 요청했을 때 등.. 이유를 모르겠네요. 임의로 `BindException`, `ConstraintViolationException` 등을 GlobalExceptionHandler에 추가했습니다.
<br>
Close #63

Logback 설정 추가

---

animory/src/main/java/com/daggle/animory/common/RefinedPage.java
animory/src/main/java/com/daggle/animory/common/config/SpringSecurityConfiguration.java
animory/src/main/java/com/daggle/animory/domain/account/AccountRepository.java
animory/src/main/java/com/daggle/animory/domain/account/AccountService.java
animory/src/main/java/com/daggle/animory/domain/pet/PetRepository.java
animory/src/main/java/com/daggle/animory/domain/shelter/ShelterService.java
animory/src/main/java/com/daggle/animory/domain/shelter/dto/response/PetProfileDto.java
animory/src/main/java/com/daggle/animory/domain/shelter/dto/response/PetProfileSlice.java
animory/src/main/java/com/daggle/animory/domain/shelter/dto/response/ShelterInfoDto.java
animory/src/main/java/com/daggle/animory/domain/shelter/dto/response/ShelterProfilePage.java
animory/src/test/java/com/daggle/animory/domain/pet/PetRepositoryTest.java
animory/src/test/java/com/daggle/animory/domain/shelter/ShelterServiceTest.java
animory/src/test/java/com/daggle/animory/testutil/datajpatest/DataJpaTestWithDummyData.java

- 특정 보호소 조회 API 구현
- account 이메일 중복 검증 API 구현 부분이 섞여 들어갔습니다.....😅
Close #91

Shelter API 내부 구현

---

animory/src/main/java/com/daggle/animory/common/error/GlobalValidationHandler.java
animory/src/main/java/com/daggle/animory/domain/fileserver/LocalFileRepository.java
animory/src/test/java/com/daggle/animory/domain/shortform/ShortFormControllerTest.java

- 파일 삭제 메소드를 생성하였습니다.
- 파일을 저장하는 save 메소드에 isEmpty 예외처리를 추가하였습니다.
- GlobalValidationHandler를 좀 더 보기 좋게 수정하였습니다.
- 추후 파일 저장방식이 바뀌면 여러모로 많은 게 변경될 것 같아 걱정이네요...
Close #97

feat: #97 파일 삭제 메소드 생성, 파일이 비어있을 경우 isEmpty 예외처리, GlobalValidationHandler 리팩토링

---

animory/src/main/java/com/daggle/animory/domain/account/AccountController.java

- 로그인 컨트롤러 수정
- Jwt 발급 및 헤더에 추가

Jwt 발급 및 헤더에 추가

---

animory/src/main/java/com/daggle/animory/common/security/TokenProvider.java
animory/src/main/java/com/daggle/animory/common/security/UserDetailsServiceImpl.java
animory/src/main/java/com/daggle/animory/domain/account/AccountController.java
animory/src/test/java/com/daggle/animory/testutil/webmvctest/BaseWebMvcTest.java

- 버그픽스 입니다. 주요 내용은 코멘트에 언급하겠습니다.
Close #103

Fix: 비정상적인 동작으로 추측되는 401 UnAuthorized Exception

---

animory/src/main/java/com/daggle/animory/domain/account/AccountService.java

- 회원가입 시 이메일이 존재하는 경우에 대한 예외 처리
Close #108

회원가입 시 중복 검증 후 저장

---

.github/workflows/gradle-test.yml
animory/.gitignore
animory/build.gradle
animory/src/main/java/com/daggle/animory/domain/fileserver/FileController.java
animory/src/main/java/com/daggle/animory/domain/fileserver/S3FileRepository.java
animory/src/main/java/com/daggle/animory/domain/pet/service/PetService.java
animory/src/main/resources/application-production.yml
animory/src/main/resources/application.yml
animory/src/test/java/com/daggle/animory/domain/fileserver/FileControllerTest.java

-  S3 사용을 위한 환경 변수 적용
-  파일 업로드 기능을 구현
- 이거 사용 경험 있으신 분이 답해주시면 좋을 것 같은데 테스트용으로 데이터 몇 개 올린다고 막 10만원씩 뜯어가는건 아니겠죠...?
- 확실히 처음 써보는 부분이라 생각 이상으로 오래걸렸습니다. 인터넷에 널려있는 걸 따라하기만 하면 정말 쉽습니다...만 이걸 진행 중인 프로젝트에 맞게 가공하고 다듬는 과정이 정말 오래걸리네요
Close #110

Feat/#110 S3기반 파일 업로드 기능 구현

---

animory/src/main/resources/application.yml

- 단순 property 파일 수정입니다.
Close #113

배포환경에서 참조하지 않는 property파일 config.import 에 optional 추가

---

animory/src/main/java/com/daggle/animory/domain/account/AccountController.java
animory/src/main/java/com/daggle/animory/domain/account/dto/request/AccountLoginDto.java
animory/src/main/java/com/daggle/animory/domain/account/dto/request/EmailValidateDto.java
animory/src/main/java/com/daggle/animory/domain/account/dto/request/ShelterAddressSignUpDto.java
animory/src/main/java/com/daggle/animory/domain/account/dto/request/ShelterSignUpDto.java
animory/src/test/java/com/daggle/animory/domain/account/AccountControllerTest.java

- 이메일 중복 검증 요청에 null값 및 이메일 형식 검증
- 회원가입 request에 Null 검증
- 회원가입 controller 유효성 검증 test 코드 추가
Close #124

Validation 및 테스트 코드 추가 

---

animory/src/main/java/com/daggle/animory/domain/pet/dto/request/PetUpdateRequestDto.java
animory/src/main/java/com/daggle/animory/domain/pet/util/PetAgeToBirthDateConverter.java
animory/src/test/java/com/daggle/animory/acceptance/AnimoryAcceptanceTest.java
animory/src/test/java/com/daggle/animory/domain/pet/util/PetAgeToBirthDateConverterTest.java
animory/src/test/java/com/daggle/animory/testutil/AcceptanceTest.java
animory/src/test/java/com/daggle/animory/testutil/WithTimeSupportObjectMapper.java
animory/src/test/java/com/daggle/animory/testutil/datajpatest/DataJpaTestWithDummyData.java

- BirthDate로부터 Age를 계산하는 메소드가 값을 그대로 반환하고 있는 오류가 있어서 수정했습니다.
- 일반적이지 않은 테스트 코드 작성에 대한 시도들이 있는데,, 나중에 다시 제거해야할지 모르겠습니다..
Close #129

PetAgeConverter 논리적 오류 수정

---

animory/src/main/resources/application-production.yml

- 현재 배포중인 서버에 SpringBoot Application 과 독립적으로 동작하는 MySQL 서버를 실행시켰고, production profile에 해당 연결정보를 추가하였습니다.
- 배포 스크립트에 환경변수로 삽입하였습니다.
- 노션에 MySQL Server Connection 정보 기록하였습니다.
Close #135

Production Profile mysql 추가

---

animory/src/main/java/com/daggle/animory/domain/shelter/ShelterRepository.java
animory/src/test/java/com/daggle/animory/domain/shelter/ShelterRepositoryTest.java

보호소 위치 필터링 Query 구문 오류 수정

---

animory/src/main/java/com/daggle/animory/common/config/WebConfiguration.java
animory/src/main/java/com/daggle/animory/common/logger/RequestLogger.java
animory/src/main/java/com/daggle/animory/common/security/RequireRole.java
animory/src/main/java/com/daggle/animory/common/security/SecurityGuard.java
animory/src/main/java/com/daggle/animory/domain/pet/controller/PetController.java

-  `@Authorized` annotation의 이름을 `@RequireRole` 로 수정하였습니다. (더 구체적이고 명확하다고 판단)
- RequestLogger를 Bean으로 관리하도록 수정하였습니다.
Close #146

5주차 코드리뷰를 통한 개선안 반영

---

animory/src/test/ux/shortform.home.html

- 직접 배포된 서비스에서 계정 생성, 동영상 업로드 이후 생성되는 S3 Url을 이용해서 HTML을 작성했습니다.
- 동영상 로딩, 재생이 굉장히 매끄러워서, 딱히 불편하지 않을 것 같습니다.
Close #152

숏폼 비디오 화면 테스트

---

animory/src/main/java/com/daggle/animory/domain/pet/util/PetAgeToBirthDateConverter.java
animory/src/test/java/com/daggle/animory/domain/pet/util/PetAgeToBirthDateConverterTest.java

- PetAge - BirthDate Converter 에서 최대값을 검사하는 부분에서 11로 수정했습니다.
Close #161

Pet Age Month 최대값 11로 수정

---

animory/build.gradle
animory/src/main/java/com/daggle/animory/common/security/JwtAuthenticationFilter.java
animory/src/main/java/com/daggle/animory/common/security/SecurityConfig.java
animory/src/main/java/com/daggle/animory/common/security/UserDetailsImpl.java
animory/src/main/java/com/daggle/animory/common/security/UserDetailsServiceImpl.java
animory/src/test/java/com/daggle/animory/domain/pet/PetControllerTest.java
animory/src/test/java/com/daggle/animory/testutil/webmvctest/BaseWebMvcTest.java

- 시큐리티 재도입에 따른 세팅
- jwt로부터 권한을 체크하는 커스텀 필터 생성
- 시큐리티 필터 체인 설정
- 커스텀한 UserDetails, UserDetailsService 구현
Close #163

시큐리티 재도입에 따른 세팅

---

animory/build.gradle
animory/src/main/java/com/daggle/animory/common/error/GlobalValidationHandler.java
animory/src/main/java/com/daggle/animory/common/logger/MethodExecutionTimeLogger.java
animory/src/main/java/com/daggle/animory/common/logger/RequestLogger.java
animory/src/main/java/com/daggle/animory/domain/fileserver/S3Configuration.java
animory/src/main/java/com/daggle/animory/domain/fileserver/S3FileRepository.java
animory/src/main/java/com/daggle/animory/domain/fileserver/S3Util.java
animory/src/main/resources/application-production.yml
animory/src/main/resources/application.yml

6주차 코드리뷰를 통한 개선안 반영

---

animory/src/main/java/com/daggle/animory/common/config/CorsConfiguration.java
animory/src/main/java/com/daggle/animory/common/config/InterceptorConfiguration.java

- WebConfiguration 파일을 둘로 분리하고 클래스 이름을 명확하게 변경하였습니다.
Close #171

Cors, Interceptor Config 분리

---

animory/src/main/java/com/daggle/animory/common/error/GlobalValidationHandler.java
animory/src/main/java/com/daggle/animory/domain/account/dto/request/ShelterAddressSignUpDto.java
animory/src/main/java/com/daggle/animory/domain/shelter/dto/request/ShelterAddressUpdateDto.java

Springdoc, Validation Error Handler등 오류 수정

---

animory/src/main/java/com/daggle/animory/common/security/SecurityConfig.java
animory/src/main/java/com/daggle/animory/common/security/TokenProvider.java
animory/src/main/java/com/daggle/animory/common/security/exception/InvalidTokenException.java
animory/src/main/java/com/daggle/animory/common/security/exception/InvalidTokenFormatException.java
animory/src/main/java/com/daggle/animory/common/security/exception/JwtExceptionFilter.java

- jwt 검증 예외처리 필터 생성
- 시큐리티 필터 체인에 추가
- 잘못 작성된 예외 메시지 수정
- Jwt 검증 시 예외처리를 추가한 코드는 이전 pr에 들어가버렸슴다..
Close #180

시큐리티 필터 내 Jwt 예외 처리

---

animory/src/main/java/com/daggle/animory/domain/pet/util/PetAgeToBirthDateConverter.java
animory/src/test/java/com/daggle/animory/acceptance/ShortFormTest.java
animory/src/test/java/com/daggle/animory/domain/pet/util/PetAgeToBirthDateConverterTest.java

- PetAgeToBirthDateConverter의 birthDateToAge에서 LocalDate를 String으로 변환할때 year가 0 일 경우 'X개월' 만 return 하도록 변경하였습니다.
- 테스트 추가하였습니다.
Close #195

나이 응답 시 1년 미만일 경우 개월수만 전송

---

animory/src/main/java/com/daggle/animory/domain/pet/dto/response/NewPetDto.java
animory/src/main/java/com/daggle/animory/domain/pet/dto/response/PetDto.java
animory/src/main/java/com/daggle/animory/domain/pet/dto/response/PetRegisterInfoDto.java
animory/src/main/java/com/daggle/animory/domain/pet/entity/AdoptionStatus.java
animory/src/main/java/com/daggle/animory/domain/pet/entity/NeutralizationStatus.java

- 입양상태, 중성화 여부가 영어로 나타나는 것을 한글로 전달합니다
- 입양 상태 (입양 완료, 미입양, 입양불가), 중성화 여부(했어요, 안했어요, 몰라요)
Close #201

입양상태, 중성화 여부 응답에 한글로 전달

---

animory/src/main/java/com/daggle/animory/domain/shortform/dto/response/ShortFormDto.java
animory/src/test/java/com/daggle/animory/acceptance/ShortFormTest.java

숏폼 누락된 입양 상태 한글로 전달

---

animory/src/main/java/com/daggle/animory/domain/pet/dto/request/PetRegisterRequestDto.java
animory/src/main/java/com/daggle/animory/domain/pet/dto/response/PetRegisterInfoDto.java
animory/src/main/java/com/daggle/animory/domain/pet/entity/Pet.java
animory/src/main/java/com/daggle/animory/domain/pet/entity/PetVideo.java
animory/src/main/java/com/daggle/animory/domain/pet/service/PetWriteServiceTransactionManager.java
animory/src/main/java/com/daggle/animory/domain/shortform/dto/response/ShortFormDto.java
animory/src/main/resources/db/migration/V3.0.0__create_petvideo.sql
animory/src/test/java/com/daggle/animory/acceptance/PetTest.java
animory/src/test/java/com/daggle/animory/testutil/fixture/PetFixture.java

- PetVideo 테이블을 Pet으로부터 분리했습니다.
- 추후 다른 Issue 추가해서 PetVideo 부분 테스트 코드 추가하겠습니다.
Close #205

좋아요 기능 구현을 위한 DB 구조 변경

---

animory/build.gradle
animory/src/main/resources/application-production.yml
animory/src/main/resources/db/migration/V3.1.0__add_created_updated_datetime_petvideo.sql

- 원인을 알 수 없는 Flyway 스크립트가 실행되지 않는 버그에 대해 테스트 하기 위한 지저분한 PR입니다.(다른 모든 방법을 시도해보았음)

Flyway 버그 수정 시도

---

animory/build.gradle

Flyway 최신버전으로 업그레이드

---

animory/src/main/java/com/daggle/animory/domain/pet/entity/PetVideo.java
animory/src/main/java/com/daggle/animory/domain/shortform/ShortFormService.java
animory/src/main/java/com/daggle/animory/domain/shortform/controller/ShortFormController.java
animory/src/main/java/com/daggle/animory/domain/shortform/controller/ShortFormControllerApi.java
animory/src/main/java/com/daggle/animory/domain/shortform/entity/PetVideoLike.java
animory/src/main/java/com/daggle/animory/domain/shortform/exception/AlreadyLikedPetVideo.java
animory/src/main/java/com/daggle/animory/domain/shortform/exception/NotLikedPetVideo.java
animory/src/main/java/com/daggle/animory/domain/shortform/exception/ShortFormExceptionMessage.java
animory/src/main/java/com/daggle/animory/domain/shortform/exception/ShortFormNotFound.java
animory/src/main/java/com/daggle/animory/domain/shortform/repository/PetVideoLikeRepository.java
animory/src/main/java/com/daggle/animory/domain/shortform/service/PetVideoLikeService.java
animory/src/main/java/com/daggle/animory/domain/shortform/service/ShortFormService.java
animory/src/main/resources/db/migration/V4.0.0__create_petvideolike.sql
animory/src/test/java/com/daggle/animory/domain/shortform/ShortFormControllerTest.java

- 좋아요 테이블 생성
- 좋아요 등록 생성 API 구현
Close #215

IP 기반 좋아요 기능 구현

---

animory/src/main/java/com/daggle/animory/domain/shortform/repository/PetVideoJpaRepository.java
animory/src/main/java/com/daggle/animory/domain/shortform/repository/PetVideoJpqlRepository.java
animory/src/main/java/com/daggle/animory/domain/shortform/service/PetVideoLikeService.java
animory/src/main/java/com/daggle/animory/domain/shortform/service/ShortFormService.java
animory/src/test/java/com/daggle/animory/acceptance/ShortFormTest.java
animory/src/test/java/com/daggle/animory/domain/shortform/repository/PetVideoJpaRepositoryOrderByTest.java

PetVideo 조회 조건 필터링의 동적 쿼리 가독성 개선

---

animory/src/main/java/com/daggle/animory/domain/shelter/ShelterService.java
animory/src/main/java/com/daggle/animory/domain/shelter/dto/request/ShelterAddressUpdateDto.java
animory/src/main/java/com/daggle/animory/domain/shelter/dto/request/ShelterUpdateDto.java
animory/src/main/java/com/daggle/animory/domain/shelter/entity/Shelter.java

- 보호소 수정 API에 zonecode 입력을 반영했습니다.
- 코드를 조금 리팩토링 했습니다.
Close #236

Shelter 수정 시 zonecode(우편번호) 입력 추가

---

Dockerfile

#238 도커파일 생성
