- animory/src/test/java/com/daggle/animory/shortform/ShortFormControllerTest.java
- WebMvcTest 가 SpringSecurityConfiguration을 사용하지 않아서 테스트가 실패하는 문제 해결
Close #41
> BugFix: WebMvcTest+ SpringSecurity Configuration

- .github/workflows/gradle-test.yml
- animory/build.gradle
- Jacoco 라고 부르는 plugin 을 추가하고, gradle test task 에 추가하였습니다.
- GitHub Actions Workflow에서 build 이후 결과를 PR에 코멘트로 추가하는 작업을 등록하였습니다.
- coverage는 50%로 설정되어있고, 충족하지 못한다고 해서 빌드가 실패하지 않게 하였습니다.
Close #69
> Java Code Coverage 측정 도구 도입 및 통합 프로세스에 추가

- animory/src/main/java/com/daggle/animory/domain/fileserver/FileController.java
- animory/src/main/java/com/daggle/animory/domain/fileserver/FileRepository.java
- animory/src/main/java/com/daggle/animory/domain/fileserver/LocalFileRepository.java
- animory/src/main/java/com/daggle/animory/domain/pet/service/fileIO/FileStorageService.java
- animory/src/main/resources/application.yml
- File Server 를 분리하려는 시도 입니다.
- 기존의 FileRepository 의 유일한 구현체는 Pet 이라는 이름과 관련이 없어서 LocalFileRepository 로 이름 변경하였습니다.
- File Server Domain Prefix 는 각 서버 별로 환경변수로 등록된 property 를 불러와서 사용하면 될 것 같습니다.(download url 제공할 때)
- File 저장이 필요한 각 다른 도메인에서 FileRepository를 가져가서 사용하면 될 듯 합니다. 추가적으로 Method name이 JPA method 와 완전 동일하다면(save, findByName 등) .. ?
Close #81
> File server 분리 초안

- animory/src/main/java/com/daggle/animory/domain/fileserver/FileController.java
- animory/src/main/java/com/daggle/animory/domain/fileserver/LocalFileRepository.java
- animory/src/test/java/com/daggle/animory/domain/fileserver/FileControllerTest.java
- 세인님께서 제안하신 의견대로 파일 요청 부분을 분리한 후 하나의 메소드로 통합하였습니다.
- 파일의 형식은 들어온 path 에 따라서 인식이 가능하니 image든 video든 전부 전달이 가능합니다.
- 한 가지 걸리는 점이 있습니다. 물론 나중에 수정이 들어갈 것 같지만 지금 파일 경로를 직접 입력받아 요청이 들어가는데, spring security에서 일부 문자를 자르는 것 같더라구요 ../으로 상위 디렉토리에 접근한다던지 이런 걸 막기 위함인것 같은데 나중에는 순수한 파일 이름이나 외부 url로 접근하도록 수정하는 게 좋아보입니다. 
예외 클래스 이름 --> org.springframework.security.web.firewall.requestrejectedexception
Close #46
> feat/#46 동영상 및 이미지 업로드 기능 구현 -> 하나의 메소드로 통합

- animory/build.gradle
- animory/src/main/java/com/daggle/animory/common/config/JpaAuditConfiguration.java
- animory/src/main/java/com/daggle/animory/common/entity/BaseEntity.java
- animory/src/main/java/com/daggle/animory/domain/account/entity/Account.java
- animory/src/main/java/com/daggle/animory/domain/pet/dto/request/PetRegisterRequestDto.java
- animory/src/main/java/com/daggle/animory/domain/pet/entity/Pet.java
- animory/src/main/java/com/daggle/animory/domain/pet/entity/PetPolygonProfile.java
- animory/src/main/java/com/daggle/animory/domain/pet/service/PetWriteService.java
- animory/src/main/java/com/daggle/animory/domain/shelter/entity/Shelter.java
- animory/src/test/java/com/daggle/animory/domain/account/AccountControllerTest.java
- animory/src/test/java/com/daggle/animory/domain/pet/PetRepositoryTest.java
- animory/src/test/java/com/daggle/animory/domain/pet/fixture/PetFixture.java
- animory/src/test/java/com/daggle/animory/testutil/datajpatest/DataJpaTestWithDummyData.java
- animory/src/test/java/com/daggle/animory/testutil/datajpatest/WithTimeSupportObjectMapper.java
- Base Entity를 추가하였습니다. createdAt과 updatedAt이라는 필드를 가지고 있는데, insert, update 가 실행될 때 자동으로 값이 추가되고 변경되도록 annotation 처리 하였습니다.
- 현재 사용중인 Pet, Shelter, Account Entity에서 상속하도록 처리하였습니다.
- test code에서 Slf4j 사용하기 위해서, lombok 의존성을 test 범위로 확장하였습니다.
Close #120
> Base Entity(createdAt, updatedAt) 추가

- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetController.java
- animory/src/main/java/com/daggle/animory/domain/pet/entity/AdoptionStatus.java
- animory/src/main/java/com/daggle/animory/domain/pet/entity/Pet.java
- animory/src/main/java/com/daggle/animory/domain/pet/service/PetWriteService.java
- AdoptionStatus 에 YES, NO 그리고 UNABLE 상태를 추가하였습니다.(보호만료일이 지났으나 미입양 상태인 동물 데이터를 위함)
- 보호소 계정에 소속된 Pet의 입양 상태를 완료로 변경하고, 보호만료일을 null로 변경하는 API를 추가했습니다.
- 입양이 완료되면, 기존 보호소와 연관관계가 사라져야 하지 않은지.. ?
Close #127
> 펫 입양완료 API 추가 

- animory/src/main/java/com/daggle/animory/domain/shelter/ShelterController.java
- animory/src/main/java/com/daggle/animory/domain/shelter/ShelterRepository.java
- animory/src/main/java/com/daggle/animory/domain/shelter/ShelterService.java
- animory/src/main/java/com/daggle/animory/domain/shelter/dto/response/ShelterLocationDto.java
- animory/src/main/java/com/daggle/animory/domain/shelter/entity/ShelterAddress.java
- animory/src/test/java/com/daggle/animory/domain/shelter/ShelterControllerTest.java
- ShelterAddress에 kakaoLocationId와 x, y 좌표 필드를 추가하였습니다. 현재 수동등록을 전제로 하고 있기 때문에 `@NotNull` 은 생략하였습니다.
- Integer List를 입력받아서, Shelter 중에 location Id 가 일치하는 목록을 Shelter 정보와 함께 리스트로 반환합니다.
- 수동 등록을 전제로 하기 때문에, 프론트엔드 팀의 테스트를 위해서도 재배포에 영향을 받지 않는 DB 서버를 구축할 필요가 있을 것 같습니다.
- Service, Repository Layer의 테스트는 다음 이슈에서 같이 작성하겠습니다.
Close #132
> 근처 동물 보호소 조회 API

- animory/src/main/java/com/daggle/animory/domain/account/dto/request/AccountLoginDto.java
- animory/src/main/java/com/daggle/animory/domain/account/dto/request/EmailValidateDto.java
- animory/src/main/java/com/daggle/animory/domain/account/dto/request/ShelterSignUpDto.java
- 이메일 빈칸 입력을 막기 위해 @NotNull에서 @NotBlank 으로 변경
- @ NotNull -> Null만 허용하지 않음
- @ NotEmpty -> null 과 "" 은 허용 X, " " 은 허용
- @ NotBlank -> null 과 "" 과 " " 모두 허용 X
Close #147
> 이메일 빈칸 입력을 막기 위한 @NotBlank 추가

- .github/workflows/gradle-test.yml
- animory/build.gradle
- `update-comment` 를 true로 변경하였습니다. 새로운 report가 생성될 때(열려있는 PR에 추가 push발생 시), 코멘트를 계속 추가해 나가지 않고 기존의 코멘트를 업데이트합니다.
- `skip-if-no-changes`를 true로 변경합니다. 변경된 파일에 대한 정보가 없으면 설명이 추가되지 않습니다.
- `pass-emoji`와 `fail-emoji`를 변경했습니다. 😍 , 😞 
- 기본적인 테스트 코드가 충분히 많아진 상태이므로 **전체 프로젝트 코드의 테스트 커버리지 통과기준을 70%로 수정하였습니다.**
- 테스트 커버리지 계산 시 SpringBoot Main Application 파일을 제외시켰습니다.
<br><br>
- 보고서에 음수로 표시되는 값에 대해서 잘 이해를 못하겠습니다. 
- 참고 이슈: https://github.com/Madrapps/jacoco-report/issues/69
<br><br>
- https://github.com/marketplace/actions/jacoco-report
- https://www.baeldung.com/jacoco-report-exclude
Close #153
> Jacoco Test Coverage PR actions 개선

- animory/src/main/java/com/daggle/animory/domain/shelter/ShelterController.java
- animory/src/main/java/com/daggle/animory/domain/shelter/ShelterService.java
- animory/src/main/java/com/daggle/animory/domain/shelter/dto/request/ShelterAddressUpdateDto.java
- animory/src/main/java/com/daggle/animory/domain/shelter/dto/request/ShelterUpdateDto.java
- animory/src/main/java/com/daggle/animory/domain/shelter/dto/response/ShelterUpdateSuccessDto.java
- animory/src/main/java/com/daggle/animory/domain/shelter/entity/Shelter.java
- animory/src/test/java/com/daggle/animory/domain/shelter/ShelterServiceTest.java
- animory/src/test/java/com/daggle/animory/testutil/fixture/AccountFixture.java
- 보호소 정보 수정 API를 구현하였습니다.
- 서비스단 테스트 코드를 작성하였습니다. 
- 수정 요청 시 기존 보호소 정보 전체를 덮어 씁니다.
Close #143
> 보호소 정보 수정 API 추가

- animory/src/main/java/com/daggle/animory/domain/account/dto/request/ShelterAddressSignUpDto.java
- animory/src/main/java/com/daggle/animory/domain/shelter/dto/request/ShelterAddressUpdateDto.java
- animory/src/main/java/com/daggle/animory/domain/shelter/entity/Province.java
- animory/src/main/java/com/daggle/animory/domain/shortform/ShortFormService.java
- animory/src/test/java/com/daggle/animory/domain/account/AccountControllerTest.java
- Province의 Enum value 자체를 변경하였습니다.
- 제주 -> 제주특별자치도
- 세종 -> 세종특별자치시
- 강원 -> 강원특별자치도
- City에 Null이 들어가는 경우를 허용하였습니다.
- ( 예시: "세종특별자치시 전의면 가나물길 13")
- Daum Postcode Service 기준, Province와 도로명주소로만 구성되어 있음.)
Close #155
> 주소 입력시, "제주특별자치도" 등의 Table Enum에 없는 문자열 처리, City Null 허용

- animory/src/main/java/com/daggle/animory/common/security/UserDetailsImpl.java
- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetController.java
- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/pet/service/PetReadService.java
- animory/src/main/java/com/daggle/animory/domain/pet/service/PetValidator.java
- animory/src/main/java/com/daggle/animory/domain/pet/service/PetWriteService.java
- animory/src/main/java/com/daggle/animory/domain/shelter/ShelterController.java
- animory/src/main/java/com/daggle/animory/domain/shelter/ShelterRepository.java
- animory/src/main/java/com/daggle/animory/domain/shelter/ShelterService.java
- animory/src/test/java/com/daggle/animory/domain/shelter/ShelterRepositoryTest.java
- animory/src/test/java/com/daggle/animory/domain/shelter/ShelterServiceTest.java
- 컨트롤러단에서 권한 인증 어노테이션을 제거
- request로 기존 Account를 받지 않고 @AuthenticationPrincipal 사용해 UserDetailsImpl 객체를 받는 것으로 수정
- UserDetailsImpl의 username인 email로 validatePetUpdateAuthority()메서드 실행
- 위 로직 변경에 따른 테스트 코드 변경
- AOP 제거 맘이 아파요
Close #165
> AOP 기반 권한 인증 제거

- animory/src/main/java/com/daggle/animory/common/error/GlobalExceptionHandler.java
- animory/src/main/java/com/daggle/animory/common/logger/MethodExecutionTimeLogger.java
- animory/src/main/java/com/daggle/animory/common/security/UserDetailsImpl.java
- animory/src/main/java/com/daggle/animory/domain/account/controller/AccountController.java
- animory/src/main/java/com/daggle/animory/domain/account/controller/AccountControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/shelter/controller/ShelterController.java
- animory/src/main/java/com/daggle/animory/domain/shelter/controller/ShelterControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/shortform/controller/ShortFormControllerApi.java
- animory/src/test/java/com/daggle/animory/domain/account/AccountControllerTest.java
- animory/src/test/java/com/daggle/animory/domain/shelter/ShelterControllerTest.java
- API 문서 내용을 추가하였습니다.(API 제목, 설명 등)
- 인증이 필요한 API의 summary에 [로그인 필요: 권한] 을 추가했습니다.
- 예상되는 예외 케이스를 모두 명시해주려고 했으나, 작업량이 많고 그만큼 유용하지 않을 듯 해서.. 하다 말았습니다.
- 메소드 실행시간 측정 로깅에서 RequestLogger(URI, METHOD, Query parameter 로그) 메소드 실행을 제외하고 ExceptionHandler 메소드 실행을 제외시켰습니다.(Exception 로그는 "실행시간 측정"과는 별개라서 뜹니다.)
Close #170 ,
Close #175
> API 문서 구체화, 불필요한 로그 제거

- animory/build.gradle
- animory/src/main/java/com/daggle/animory/common/RefinedPage.java
- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetController.java
- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/shelter/ShelterService.java
- animory/src/main/java/com/daggle/animory/domain/shelter/controller/ShelterController.java
- animory/src/main/java/com/daggle/animory/domain/shelter/controller/ShelterControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/shortform/ShortFormService.java
- animory/src/main/java/com/daggle/animory/domain/shortform/controller/ShortFormController.java
- animory/src/main/java/com/daggle/animory/domain/shortform/controller/ShortFormControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/shortform/dto/request/ShortFormSearchCondition.java
- animory/src/main/resources/application.yml
- animory/src/test/java/com/daggle/animory/domain/shelter/ShelterControllerTest.java
- animory/src/test/java/com/daggle/animory/domain/shelter/ShelterServiceTest.java
- animory/src/test/java/com/daggle/animory/domain/shortform/ShortFormControllerTest.java
- API 문서의 입력 양식을 좀 더 깔끔하게 변경했습니다.
(한계는, Sprindoc 그리고 Swagger에서 현재 multipart/form-data 내에서 application/json 형식의 데이터를 같이 보내는 형식을 지원하지 않는 것 같습니다.(https://github.com/springdoc/springdoc-openapi/issues/820)
- Page입력값 관련부분은 코멘트에 상세 작업내용 추가하겠습니다.
Close #183
> Page 입력 초기값 1로 변경, API 문서 개선

- animory/src/main/java/com/daggle/animory/common/security/TokenProvider.java
- animory/src/main/java/com/daggle/animory/domain/account/AccountService.java
- animory/src/main/java/com/daggle/animory/domain/account/controller/AccountController.java
- animory/src/main/java/com/daggle/animory/domain/account/dto/TokenWithExpirationDateTimeDto.java
- animory/src/main/java/com/daggle/animory/domain/account/dto/response/AccountInfo.java
- animory/src/main/java/com/daggle/animory/domain/account/dto/response/AccountLoginSuccessDto.java
- animory/src/main/java/com/daggle/animory/domain/pet/service/PetValidator.java
- animory/src/main/java/com/daggle/animory/domain/shelter/dto/response/PetProfileDto.java
- animory/src/test/java/com/daggle/animory/acceptance/AccountTest.java
- animory/src/test/java/com/daggle/animory/domain/account/AccountControllerTest.java
- 로그인이 특정 AccountRole에 종속적으로 동작하지 않게 변경했습니다.(switch문 참조)
- 로그인 응답 시, "토큰에 들어있는 만료기한을 Body에 중복으로 넣어서 응답" 추가하였습니다.(#184 참조)
- Shelter Profile 조회 Dto에 imageUrl, age 추가하였습니다.
Close #184  ,
Close #185 ,
Close #188
> 로그인 API, Shelter Profile Dto 변경

- animory/src/main/java/com/daggle/animory/common/security/JwtAuthenticationFilter.java
- animory/src/main/java/com/daggle/animory/common/security/SecurityConfig.java
- animory/src/main/java/com/daggle/animory/common/security/TokenProvider.java
- animory/src/main/java/com/daggle/animory/domain/shelter/dto/response/PetProfilePage.java
- animory/src/main/java/com/daggle/animory/domain/shelter/dto/response/ShelterProfilePage.java
- animory/src/test/java/com/daggle/animory/acceptance/PetTest.java
- JwtAuthenticationFilter 에서 JwtException이 터지면 JwtAuthenticationFilter 바로 뒤의 JwtExceptionFilter가 처리하도록 하였으나,
- HandlerExceptionResolver가 채가 authenticationEntryPoint한테 전달하여 처리하는 듯합니다.(이때 JwtException형태가 아닌 InsufficientAuthenticationException로 변경되어 전달됨)
- 그 후에 JwtExceptionFilter가 다시 JwtException를 처리하여 응답 Body가 두 번 작성됩니다.
- 위 상황을 해결하기 위해 가능한 모든 시도 해봤으나
- 현 상황에서 최선은 authenticationEntryPoint에서 HandlerExceptionResolver를 제거하고 JwtExceptionFilter에서 처리한 응답을 전달하도록 수정하였습니다.
- 다른 좋은 방법이 있다면 말해주세요.
Close #186
> JwtException 발생 시 응답 Body가 두번 나가는 버그 해결

- animory/src/main/java/com/daggle/animory/common/exception/handler/GlobalExceptionHandler.java
- animory/src/main/java/com/daggle/animory/common/security/JwtAuthenticationFilter.java
- animory/src/main/java/com/daggle/animory/common/security/SecurityConfig.java
- animory/src/main/java/com/daggle/animory/common/security/TokenProvider.java
- animory/src/main/java/com/daggle/animory/common/security/UserDetailsServiceImpl.java
- animory/src/main/java/com/daggle/animory/common/security/exception/InvalidTokenException.java
- animory/src/main/java/com/daggle/animory/common/security/exception/InvalidTokenFormatException.java
- animory/src/main/java/com/daggle/animory/common/security/exception/UnAuthorizedException.java
- animory/src/main/java/com/daggle/animory/domain/account/controller/AccountControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/pet/service/PetReadService.java
- animory/src/main/java/com/daggle/animory/domain/pet/service/PetWriteService.java
- animory/src/main/java/com/daggle/animory/domain/shelter/controller/ShelterControllerApi.java
- swagger에 해당하는 예외만 나타나도록 수정 및 예외 명세 자세히
- 사용하지 않는 Custom Exception 삭제
- Swagger에서 @ApiResponse 작성 시 동일한 responseCode가 여러개 있을 경우 한개만 표시됩니다.
Close #182
> swagger api에 해당하는 커스텀 예외만 표시 및 예외문서화 상세화

- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetController.java
- animory/src/main/java/com/daggle/animory/domain/pet/repository/PetRepository.java
- animory/src/main/java/com/daggle/animory/domain/pet/service/PetReadService.java
- animory/src/test/java/com/daggle/animory/domain/pet/PetRepositoryTest.java
- animory/src/test/java/com/daggle/animory/testutil/datajpatest/DataJpaTestWithDummyData.java
- animory/src/test/java/com/daggle/animory/testutil/fixture/PetFixture.java
- 긴급 도움 페이지 조회 시 보호만료기간이 Null값인 경우 제외하도록 @Pageable 에서 sort 제외
- 추가로, 2021.03.04 처럼 now() 기준으로 보호만료기간이 지난 경우는 조회되지 않도록 했습니다. 
Close #197
> 긴급 도움 페이지 조회 시 보호만료기간이 Null값인 경우 제외

- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetController.java
- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/pet/entity/Pet.java
- animory/src/main/java/com/daggle/animory/domain/pet/entity/PetVideo.java
- animory/src/main/java/com/daggle/animory/domain/pet/repository/PetRepository.java
- animory/src/main/java/com/daggle/animory/domain/shelter/controller/ShelterController.java
- animory/src/main/java/com/daggle/animory/domain/shelter/controller/ShelterControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/shelter/entity/Shelter.java
- animory/src/main/java/com/daggle/animory/domain/shortform/ShortFormService.java
- animory/src/main/java/com/daggle/animory/domain/shortform/controller/ShortFormController.java
- animory/src/main/java/com/daggle/animory/domain/shortform/controller/ShortFormControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/shortform/repository/PetVideoRepository.java
- animory/src/main/resources/application-production.yml
- animory/src/test/java/com/daggle/animory/domain/pet/PetRepositoryTest.java
- animory/src/test/java/com/daggle/animory/domain/pet/util/PetAgeToBirthDateConverterTest.java
- animory/src/test/java/com/daggle/animory/domain/shortform/ShortFormRepositoryTest.java
- animory/src/test/java/com/daggle/animory/testutil/WithTimeSupportObjectMapper.java
- animory/src/test/java/com/daggle/animory/testutil/datajpatest/DataJpaTestWithDummyData.java
- animory/src/test/java/com/daggle/animory/testutil/fixture/PetFixture.java
- [실수] Production Profile에 누락되어 있던 Pageable 입력 값을 기본 1로 잡아주는 설정을 추가했습니다.
- [실수] PetAge 변환 시 year가 0인 경우에 대한 테스트 동작 변경이 누락되어 있어서 추가했습니다.(Autoparams의 테스트 데이터 랜덤생성으로 우연히 얻어걸렸는데, 애초에 테스트 케이스를 확실하게 넣어뒀어야 해서 안좋은건지 아니면 예상하지 못했던 테스트케이스가 발생해서 잡아냈기 때문에 좋은건지 모르겠네요)
- **[중요]** `@PageableDefault` 에서 기본값을 1로 잡아주면, `spring.data.web.pageable.one-indexed-parameters: true` 설정과 충돌하게 되네요. 기본(no-parameter)입력으로 요청 시 page가 2가 됩니다. 따라서 0으로 잡아둬야합니다. 명시적으로 1로 입력하고 요청할 시에는 그대로 1이 됩니다. 구체적인 이유는 찾아보지 않았습니다.
- [사소한 개선] ShortForm API 문서에 pageable 그대로 노출되어 있는 api 하나 수정했습니다.(#198)
- [기본기 부족] OneToMany 동작을 제대로 이해하고 fk가 들어가도록 로직을 수정했습니다. 결론적으로 `@OneToMany` 사용의 장점은 아직 크게 모르겠지만, 지금처럼 기존 테이블에서 떨어져나가 새로운 테이블로 확장되어 나가는 경우에 유지보수 비용을 크게(매우 압도적으로, 또는 비현실적인 것을 현실적으로) 줄여주는 것 같습니다.
- [깨달음] DataJpaTest를 위한 BaseClass에서 반환된 entity를 콘솔에 …
> PageableDefault, 변경된 DB 구조, 이전 테스트 실패 등에 관련한 각종 BugFix

- animory/src/main/java/com/daggle/animory/common/exception/handler/GlobalExceptionHandler.java
- animory/src/main/java/com/daggle/animory/domain/pet/entity/PetVideo.java
- animory/src/main/java/com/daggle/animory/domain/shortform/ShortFormService.java
- animory/src/main/java/com/daggle/animory/domain/shortform/dto/response/CategoryShortFormPage.java
- animory/src/main/java/com/daggle/animory/domain/shortform/dto/response/HomeShortFormPage.java
- animory/src/main/java/com/daggle/animory/domain/shortform/dto/response/ShortFormDto.java
- animory/src/main/java/com/daggle/animory/domain/shortform/repository/PetVideoRepository.java
- animory/src/main/java/com/daggle/animory/domain/shortform/util/LikeCountToStringConverter.java
- animory/src/main/resources/db/migration/V3.1.0__add_created_updated_datetime_petvideo.sql
- animory/src/test/java/com/daggle/animory/acceptance/ShortFormTest.java
- animory/src/test/java/com/daggle/animory/domain/shelter/ShelterRepositoryTest.java
- animory/src/test/java/com/daggle/animory/domain/shortform/repository/PetVideoRepositoryOrderByTest.java
- animory/src/test/java/com/daggle/animory/domain/shortform/repository/PetVideoRepositoryTest.java
- animory/src/test/java/com/daggle/animory/domain/shortform/util/LikeCountToStringConverterTest.java
- animory/src/test/resources/sql/PetVideoRepositoryOrderByTest.sql
- LikeCount를 short form api 응답에 추가
- 문자열변환(1000개가 넘어가면 1.x천개 등)
- 테스트
- PetVideo에 BaseEntity 상속(creadted,updated time)
- PetVideo 조회에 like 지표를 추가하고 랜덤으로 섞는 로직 추가
Close #209
> 숏폼 영상 조회 플로우에 Like 지표를 이용한 조회 기준 적용, 기존 API 응답에 Like값 추가

- animory/src/main/java/com/daggle/animory/domain/shortform/ShortFormService.java
- animory/src/main/java/com/daggle/animory/domain/shortform/repository/PetVideoRepository.java
- animory/src/main/resources/application-production.yml
- animory/src/main/resources/application.yml
- animory/src/test/java/com/daggle/animory/domain/shortform/repository/PetVideoRepositoryOrderByTest.java
- animory/src/test/java/com/daggle/animory/domain/shortform/repository/PetVideoRepositoryTest.java
- Fetch Join과 Pageable Query를 동시에 사용할 때, JPA는 의도한 대로 동작하지  않고 모든 값을 메모리에 가져와서 Pagination을 수행한다고 합니다.(이유는 모르겠음) 이 쿼리는 서비스 진입점인 홈페이지에서 가장 많이 실행되는 쿼리이기도 하고, EC2 Free Tier의 1GB 메모리를 괴롭히고 싶지 않기도하고 warning log가 잔뜩 쌓이는 것을 지우기 위해 수정해보았습니다. native query를 사용해서 1회의 쿼리로 실행하게 할 수도 있을 것 같은데 복잡하고 관리비용이 너무 커질 것이라 생각해서 쿼리를 단순히 2개로 분할하였습니다.
Close #216
> ShortForm Repository의 Fetch Join과 Pagination query 분리

- animory/build.gradle
- animory/src/main/resources/application-production.yml
- animory/src/main/resources/application.yml
- 서버가 안정적으로 작동 중인지 확인하고, 자동 복구 시스템을 구축하기 위한 Health Check 목적의 Actuator 종속성과 설정을 추가하였습니다.
관련 이슈: #225
> SpringBoot Actuator 추가

- animory/src/main/java/com/daggle/animory/domain/account/dto/request/ShelterAddressSignUpDto.java
- animory/src/main/java/com/daggle/animory/domain/account/dto/request/ShelterSignUpDto.java
- animory/src/main/java/com/daggle/animory/domain/shelter/entity/ShelterAddress.java
- animory/src/main/resources/db/migration/V4.1.0__add_zone_code.sql
- animory/src/test/java/com/daggle/animory/acceptance/AccountTest.java
- animory/src/test/java/com/daggle/animory/acceptance/ShelterTest.java
- animory/src/test/java/com/daggle/animory/testutil/fixture/ShelterFixture.java
- 데이터베이스의 보호소 주소에 우편번호(zonecode)를 추가하고 기존의 API Request형식을 바꾸지 않는 선에서, 저장하는 로직을 수정하였습니다.
Close #234
> 보호소 정보 수정 페이지를 위한 우편번호 관리 추가

- animory/src/main/java/com/daggle/animory/common/config/EnumConverterConfiguration.java
- animory/src/main/java/com/daggle/animory/domain/shelter/ProvinceConverter.java
- animory/src/main/java/com/daggle/animory/domain/shelter/entity/Province.java
- animory/src/main/java/com/daggle/animory/domain/shelter/entity/ShelterAddress.java
- animory/src/test/java/com/daggle/animory/domain/account/AccountControllerTest.java
- Jackson의 `@JsonCreator`와 Converter 를 사용해서 처리했습니다.
- DB에서 Province가 integer 타입으로 관리되고 있어서 `@Enumetrated String` 설정 추가했습니다(기존 데이터도 모두 변경)
Close #240 ,
Close #241
> Province Enum 입력 값에 대한 유연한 처리(제주, 제주도, 제주특별자치도 등)

- animory/src/main/java/com/daggle/animory/domain/account/controller/AccountControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/shelter/controller/ShelterControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/shortform/controller/ShortFormControllerApi.java
- 가능한 모든 예외 상황을 API 문서에 반영
- 누락된 부분 또는 설명이 미흡한 부분 검토 및 수정
Close #246
> 스웨거 API 예외 응답 점검

- animory/src/main/java/com/daggle/animory/common/exception/handler/GlobalExceptionHandler.java
- animory/src/main/java/com/daggle/animory/common/security/JwtAuthenticationFilter.java
- animory/src/main/java/com/daggle/animory/common/security/SecurityConfig.java
- animory/src/main/java/com/daggle/animory/common/security/TokenProvider.java
- animory/src/main/java/com/daggle/animory/common/security/exception/JwtExceptionFilter.java
- animory/src/main/java/com/daggle/animory/common/security/exception/UnAuthorizedException.java
- animory/src/test/java/com/daggle/animory/acceptance/PetTest.java
1. 토큰이 아예 존재하지 않는 경우
2. 토큰이 존재하지만 검사를 통과하지 못하는 경우
에 각각 응답이 형식에 맞게 반환되도록 수정하였습니다.
Close #250
> Security Exception Handling에서 응답이 제대로 나오도록 처리

- animory/src/main/java/com/daggle/animory/common/exception/handler/GlobalExceptionHandler.java
- animory/src/main/java/com/daggle/animory/domain/shortform/exception/AlreadyLikedPetVideoException.java
- animory/src/main/java/com/daggle/animory/domain/shortform/exception/NotLikedPetVideoException.java
- animory/src/main/java/com/daggle/animory/domain/shortform/exception/ShortFormNotFoundException.java
- animory/src/main/java/com/daggle/animory/domain/shortform/service/PetVideoLikeService.java
- GlobalExceptionHandler에 누락된 숏폼 커스텀 예외 처리 추가
- 기존 커스텀 exception와 통일성을 위해 숏폼 커스텀 에러 이름에 Exception 추가
Close #249
> GlobalExceptionHandler에 누락된 커스텀 예외 처리 추가

- animory/src/main/java/com/daggle/animory/common/security/exception/SecurityExceptionMessage.java
- animory/src/main/java/com/daggle/animory/domain/pet/service/PetReadService.java
- 프로필 목록 페이지 조회 시 프로필 긴급, 신규 각각 4개씩 전달
- 시큐리티 패키지의 ExceptionMessage에 사용하지 않는 예외들 제거
- 더보기로 진입하는 긴급 조회 페이지, 신규 조회 페이지의 프로필은 여전히 8개로 반환합니다!
Close #253
> 프로필 목록 페이지 조회 시 프로필 긴급, 신규 각각 4개씩 전달

- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetController.java
- animory/src/main/java/com/daggle/animory/domain/pet/controller/PetControllerApi.java
- animory/src/main/java/com/daggle/animory/domain/pet/dto/response/NewPetDto.java
- animory/src/main/java/com/daggle/animory/domain/pet/dto/response/SosPetDto.java
- animory/src/main/java/com/daggle/animory/domain/pet/entity/PetVideo.java
- animory/src/main/java/com/daggle/animory/domain/shortform/dto/response/ShortFormDto.java
- animory/src/main/java/com/daggle/animory/domain/shortform/repository/PetVideoJpaRepository.java
- animory/src/main/java/com/daggle/animory/domain/shortform/repository/PetVideoJpqlRepository.java
- animory/src/main/resources/application.yml
Close #224 ,
Close #256 ,
Close #257
> UI 관련 API 수정 요청 반영, PetVideo 조회 로직의 오류 수정 등
